package parser;

public interface ISyntaxAnalyzer {

   public boolean compile(); //initiates compilation or parsing process
   public String output(); //returns compilation errors, relevant results, parse trees
   public String intermediateCode(); //returns the intermediate code generated by the parser
   public String symbolTable(); //returns the symbol table generated by the parser

}
